### ISSUE TITLE
Missing aceProvider setup instructions.

### ISSUE THREAD

**Issue by duartealexf** [APCOvernight/adonis-schema-builder#4]
Hi there. Great job in this package.. beautiful code too.

I just installed the package but it only worked after I added this...

```
'adonis-schema-builder/providers/BuilderProvider'
```

...to aceProviders array.

I was going to create a PR to fix this, but I can't push due to permissions. Anyways, either add me to contribute or fix this, please.

Thanks.

**Comment by webdevian** [comment]
Fixed in v0.1.4
